/**
 * Vision AI — WASSCE Knowledge Base
 * Structured knowledge about Ghana Senior High School curriculum.
 * All content built from scratch based on the WAEC syllabus.
 */

const KNOWLEDGE_BASE = [

  // ─── CORE MATHEMATICS ──────────────────────────────────────────────────────
  { id: 'math-001', subject: 'mathematics', topic: 'algebra', text: 'To solve a linear equation, isolate the variable by performing inverse operations on both sides. Example: 2x + 5 = 13 → 2x = 8 → x = 4. Always check your answer by substituting back.', tags: ['linear', 'equation', 'solve', 'algebra'] },
  { id: 'math-002', subject: 'mathematics', topic: 'algebra', text: 'Quadratic equations have the form ax² + bx + c = 0. Use the quadratic formula: x = (-b ± √(b²-4ac)) / 2a. The discriminant b²-4ac tells you the nature of roots: positive = 2 real roots, zero = 1 repeated root, negative = no real roots.', tags: ['quadratic', 'formula', 'roots', 'discriminant'] },
  { id: 'math-003', subject: 'mathematics', topic: 'indices', text: 'Laws of indices (exponents): a^m × a^n = a^(m+n), a^m ÷ a^n = a^(m-n), (a^m)^n = a^(mn), a^0 = 1, a^(-n) = 1/a^n, a^(1/n) = ⁿ√a. These apply only when the base is the same.', tags: ['indices', 'exponents', 'laws', 'power'] },
  { id: 'math-004', subject: 'mathematics', topic: 'logarithms', text: 'Logarithm laws: log(ab) = log(a) + log(b), log(a/b) = log(a) - log(b), log(a^n) = n·log(a), log_a(a) = 1, log_a(1) = 0. Natural log uses base e. Common log uses base 10.', tags: ['logarithm', 'log', 'laws', 'natural'] },
  { id: 'math-005', subject: 'mathematics', topic: 'sets', text: 'Set operations: Union (A∪B) contains elements in A or B. Intersection (A∩B) contains elements in both A and B. Complement (A\') contains elements not in A. De Morgan\'s laws: (A∪B)\' = A\'∩B\', (A∩B)\' = A\'∪B\'.', tags: ['sets', 'union', 'intersection', 'complement', 'venn'] },
  { id: 'math-006', subject: 'mathematics', topic: 'probability', text: 'Probability P(E) = number of favourable outcomes / total outcomes. P(A∪B) = P(A) + P(B) - P(A∩B). For independent events: P(A∩B) = P(A) × P(B). Complement: P(A\') = 1 - P(A). Probability always lies between 0 and 1.', tags: ['probability', 'events', 'independent', 'complement'] },
  { id: 'math-007', subject: 'mathematics', topic: 'statistics', text: 'Measures of central tendency: Mean = sum of values / number of values. Median = middle value when sorted. Mode = most frequent value. Measures of spread: Range = max - min. Standard deviation measures how spread out data is from the mean.', tags: ['statistics', 'mean', 'median', 'mode', 'range', 'standard deviation'] },
  { id: 'math-008', subject: 'mathematics', topic: 'geometry', text: 'Circle theorems: angle at centre = 2 × angle at circumference (same arc). Angles in same segment are equal. Angle in semicircle = 90°. Opposite angles of cyclic quadrilateral sum to 180°. Tangent is perpendicular to radius at point of contact.', tags: ['circle', 'theorem', 'angle', 'geometry', 'tangent'] },
  { id: 'math-009', subject: 'mathematics', topic: 'trigonometry', text: 'SOHCAHTOA: sin θ = opposite/hypotenuse, cos θ = adjacent/hypotenuse, tan θ = opposite/adjacent. Pythagorean identity: sin²θ + cos²θ = 1. Sine rule: a/sinA = b/sinB = c/sinC. Cosine rule: a² = b² + c² - 2bc·cosA.', tags: ['trigonometry', 'sin', 'cos', 'tan', 'SOHCAHTOA', 'sine rule', 'cosine rule'] },
  { id: 'math-010', subject: 'mathematics', topic: 'vectors', text: 'A vector has magnitude and direction. Vector addition: (a,b) + (c,d) = (a+c, b+d). Scalar multiplication: k(a,b) = (ka,kb). Magnitude: |v| = √(a²+b²). Unit vector: v/|v|. Position vector of midpoint M of AB = (OA + OB)/2.', tags: ['vectors', 'magnitude', 'direction', 'position vector', 'midpoint'] },
  { id: 'math-011', subject: 'mathematics', topic: 'sequences', text: 'Arithmetic Progression (AP): nth term = a + (n-1)d. Sum of n terms = n/2 × (2a + (n-1)d). Geometric Progression (GP): nth term = ar^(n-1). Sum of n terms = a(1-rⁿ)/(1-r). Sum to infinity (|r|<1) = a/(1-r).', tags: ['sequences', 'arithmetic progression', 'geometric progression', 'AP', 'GP', 'series'] },
  { id: 'math-012', subject: 'mathematics', topic: 'mensuration', text: 'Area formulas: triangle = ½bh, circle = πr², rectangle = lw, trapezium = ½(a+b)h. Volume: sphere = 4/3πr³, cylinder = πr²h, cone = 1/3πr²h, cuboid = lwh. Surface area: sphere = 4πr², cylinder = 2πr(r+h).', tags: ['mensuration', 'area', 'volume', 'surface area', 'circle', 'sphere', 'cylinder'] },
  { id: 'math-013', subject: 'mathematics', topic: 'functions', text: 'A function f maps each input x to exactly one output f(x). Domain is the set of valid inputs. Range is the set of outputs. Composite function: (f∘g)(x) = f(g(x)). Inverse function f⁻¹ reverses the mapping. Vertical line test checks if a graph is a function.', tags: ['function', 'domain', 'range', 'inverse', 'composite', 'mapping'] },

  // ─── ENGLISH LANGUAGE ──────────────────────────────────────────────────────
  { id: 'eng-001', subject: 'english', topic: 'grammar', text: 'Parts of speech: Noun (person, place, thing), Verb (action, state), Adjective (modifies noun), Adverb (modifies verb/adjective), Pronoun (replaces noun), Preposition (shows relation), Conjunction (joins clauses), Interjection (exclamation).', tags: ['grammar', 'parts of speech', 'noun', 'verb', 'adjective', 'adverb'] },
  { id: 'eng-002', subject: 'english', topic: 'comprehension', text: 'For comprehension passages: read the questions first, then read the passage actively. Find the main idea of each paragraph. Answer in your own words unless asked to quote. Use evidence from the text to support answers. Check word limits.', tags: ['comprehension', 'reading', 'passage', 'main idea', 'evidence'] },
  { id: 'eng-003', subject: 'english', topic: 'essay', text: 'Essay structure: Introduction (hook + thesis statement), Body paragraphs (topic sentence + evidence + analysis + transition), Conclusion (restate thesis + summary + closing thought). Use varied sentence structures and formal language in academic essays.', tags: ['essay', 'writing', 'introduction', 'body', 'conclusion', 'paragraph'] },
  { id: 'eng-004', subject: 'english', topic: 'figures of speech', text: 'Common figures of speech: Simile (comparison using "like/as"), Metaphor (direct comparison), Personification (human qualities to non-human), Hyperbole (exaggeration), Irony (opposite meaning), Alliteration (repeated consonant sounds), Onomatopoeia (words that sound like what they mean).', tags: ['figures of speech', 'simile', 'metaphor', 'personification', 'hyperbole', 'irony'] },
  { id: 'eng-005', subject: 'english', topic: 'sentence structure', text: 'Sentence types: Simple (one independent clause), Compound (two independent clauses joined by coordinating conjunction), Complex (independent + dependent clause), Compound-complex. Common errors: run-on sentences, sentence fragments, subject-verb disagreement.', tags: ['sentence', 'clause', 'simple', 'compound', 'complex', 'grammar'] },
  { id: 'eng-006', subject: 'english', topic: 'tenses', text: 'Tenses: Simple present (I write), Simple past (I wrote), Simple future (I will write). Perfect: Present perfect (I have written), Past perfect (I had written). Continuous: Present continuous (I am writing), Past continuous (I was writing). Sequence of tenses must be consistent.', tags: ['tense', 'past', 'present', 'future', 'perfect', 'continuous'] },
  { id: 'eng-007', subject: 'english', topic: 'letter writing', text: 'Formal letter format: Sender\'s address (top right), Date, Recipient\'s address, Salutation (Dear Sir/Madam), Body (paragraphs), Complimentary close (Yours faithfully if name unknown, Yours sincerely if name known), Signature, Full name. Keep formal language throughout.', tags: ['letter', 'formal', 'writing', 'format', 'salutation', 'address'] },

  // ─── INTEGRATED SCIENCE ────────────────────────────────────────────────────
  { id: 'sci-001', subject: 'science', topic: 'cells', text: 'Cell types: Prokaryotic (no membrane-bound nucleus, e.g. bacteria) and Eukaryotic (membrane-bound nucleus, e.g. plant and animal cells). Plant cells have cell wall, chloroplasts, and large vacuole. Animal cells have centrioles and no cell wall.', tags: ['cell', 'prokaryotic', 'eukaryotic', 'plant cell', 'animal cell', 'nucleus'] },
  { id: 'sci-002', subject: 'science', topic: 'photosynthesis', text: 'Photosynthesis equation: 6CO₂ + 6H₂O + light energy → C₆H₁₂O₆ + 6O₂. It occurs in chloroplasts. Light-dependent reactions produce ATP and NADPH. Light-independent (Calvin cycle) uses ATP to fix CO₂ into glucose. Factors affecting rate: light intensity, CO₂ concentration, temperature.', tags: ['photosynthesis', 'chloroplast', 'glucose', 'carbon dioxide', 'oxygen', 'light'] },
  { id: 'sci-003', subject: 'science', topic: 'respiration', text: 'Aerobic respiration: C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + 38 ATP. Occurs in mitochondria. Anaerobic (no oxygen): in animals → lactic acid, in yeast → ethanol + CO₂ (fermentation). Aerobic releases more energy than anaerobic.', tags: ['respiration', 'aerobic', 'anaerobic', 'ATP', 'mitochondria', 'fermentation'] },
  { id: 'sci-004', subject: 'science', topic: 'atoms', text: 'Atomic structure: Nucleus contains protons (positive) and neutrons (neutral). Electrons (negative) orbit in shells. Atomic number = number of protons. Mass number = protons + neutrons. Isotopes have same protons but different neutrons. Electronic configuration: 2,8,8,... per shell.', tags: ['atom', 'proton', 'neutron', 'electron', 'nucleus', 'isotope', 'atomic number'] },
  { id: 'sci-005', subject: 'science', topic: 'periodic table', text: 'Periodic table: Elements arranged by increasing atomic number. Groups (columns) have similar chemical properties. Periods (rows) show increasing atomic number. Metals on left, non-metals on right, metalloids on boundary. Group 1 = alkali metals, Group 7 = halogens, Group 0 = noble gases.', tags: ['periodic table', 'element', 'group', 'period', 'metal', 'non-metal', 'noble gas'] },
  { id: 'sci-006', subject: 'science', topic: 'forces', text: 'Newton\'s laws: 1st - object remains at rest or uniform motion unless acted on by force. 2nd - F = ma (force = mass × acceleration). 3rd - every action has equal and opposite reaction. Weight W = mg. Friction opposes motion. Pressure = force/area.', tags: ['force', 'newton', 'motion', 'acceleration', 'friction', 'pressure', 'weight'] },
  { id: 'sci-007', subject: 'science', topic: 'waves', text: 'Wave properties: Amplitude (height), Wavelength (distance per cycle), Frequency (cycles per second, Hz), Period (time per cycle). Wave speed = frequency × wavelength. Transverse waves (light, water) oscillate perpendicular to direction. Longitudinal waves (sound) oscillate parallel to direction.', tags: ['wave', 'amplitude', 'wavelength', 'frequency', 'transverse', 'longitudinal', 'sound', 'light'] },
  { id: 'sci-008', subject: 'science', topic: 'electricity', text: 'Ohm\'s law: V = IR (voltage = current × resistance). Power P = IV = I²R = V²/R. In series circuits: total resistance = sum of individual resistances, same current throughout. In parallel: 1/R_total = 1/R1 + 1/R2, voltage same across each branch.', tags: ['electricity', 'ohm', 'voltage', 'current', 'resistance', 'series', 'parallel', 'circuit'] },

  // ─── ELECTIVE MATHEMATICS ──────────────────────────────────────────────────
  { id: 'emath-001', subject: 'elective-maths', topic: 'calculus', text: 'Differentiation rules: d/dx(xⁿ) = nxⁿ⁻¹. Chain rule: d/dx[f(g(x))] = f\'(g(x))·g\'(x). Product rule: d/dx(uv) = u\'v + uv\'. Quotient rule: d/dx(u/v) = (u\'v - uv\')/v². Differentiation finds gradient/rate of change; integration finds area under curve.', tags: ['calculus', 'differentiation', 'derivative', 'chain rule', 'product rule'] },
  { id: 'emath-002', subject: 'elective-maths', topic: 'integration', text: 'Integration rules: ∫xⁿdx = xⁿ⁺¹/(n+1) + C (n≠-1). ∫1/x dx = ln|x| + C. ∫eˣdx = eˣ + C. Definite integral ∫ₐᵇf(x)dx = F(b) - F(a). Area between curve and x-axis. Integration is the reverse of differentiation.', tags: ['integration', 'integral', 'area', 'definite', 'indefinite', 'calculus'] },
  { id: 'emath-003', subject: 'elective-maths', topic: 'matrices', text: 'Matrix multiplication: (AB)ᵢⱼ = sum of row i of A × column j of B. Only possible if columns of A = rows of B. Determinant of 2×2 matrix [a,b;c,d] = ad - bc. Inverse: A⁻¹ = (1/det A) × adjugate. Identity matrix I satisfies AI = IA = A.', tags: ['matrix', 'matrices', 'determinant', 'inverse', 'multiplication', 'identity'] },
  { id: 'emath-004', subject: 'elective-maths', topic: 'permutations', text: 'Permutations (order matters): P(n,r) = n!/(n-r)!. Combinations (order doesn\'t matter): C(n,r) = n!/[r!(n-r)!]. Factorial: n! = n×(n-1)×...×1. The binomial theorem: (a+b)ⁿ = Σ C(n,r)aⁿ⁻ʳbʳ for r=0 to n.', tags: ['permutation', 'combination', 'factorial', 'binomial', 'counting'] },

  // ─── ECONOMICS ─────────────────────────────────────────────────────────────
  { id: 'eco-001', subject: 'economics', topic: 'demand', text: 'Law of demand: as price rises, quantity demanded falls (inverse relationship), ceteris paribus. Demand curve slopes downward. Factors shifting demand: income, prices of related goods, tastes, expectations, number of buyers. Price elasticity of demand = % change in Qd / % change in price.', tags: ['demand', 'law of demand', 'price', 'elasticity', 'demand curve'] },
  { id: 'eco-002', subject: 'economics', topic: 'supply', text: 'Law of supply: as price rises, quantity supplied rises (positive relationship). Supply curve slopes upward. Factors shifting supply: input costs, technology, taxes/subsidies, expectations, number of sellers. Market equilibrium where supply = demand — price where market clears.', tags: ['supply', 'law of supply', 'equilibrium', 'price', 'market'] },
  { id: 'eco-003', subject: 'economics', topic: 'national income', text: 'GDP (Gross Domestic Product) = total value of goods/services produced in a country in a year. Measured by: Expenditure method (C+I+G+(X-M)), Income method (wages+rent+interest+profit), Output method. GNP = GDP + net factor income from abroad. Real GDP adjusts for inflation.', tags: ['GDP', 'national income', 'GNP', 'expenditure', 'income', 'inflation'] },
  { id: 'eco-004', subject: 'economics', topic: 'money', text: 'Functions of money: medium of exchange, store of value, unit of account, standard of deferred payment. Types: commodity money, fiat money, credit money. Money supply expanded through fractional reserve banking. Central bank controls money supply through open market operations, reserve requirements, discount rate.', tags: ['money', 'functions', 'central bank', 'money supply', 'banking'] },

  // ─── SOCIAL STUDIES ────────────────────────────────────────────────────────
  { id: 'soc-001', subject: 'social-studies', topic: 'government', text: 'Ghana operates under a republican constitutional democracy. The 1992 Constitution establishes three arms of government: Legislature (Parliament makes laws), Executive (President enforces laws), Judiciary (Courts interpret laws). Separation of powers prevents abuse. The Electoral Commission manages elections.', tags: ['government', 'Ghana', 'constitution', 'legislature', 'executive', 'judiciary', 'democracy'] },
  { id: 'soc-002', subject: 'social-studies', topic: 'citizenship', text: 'A citizen has rights (fundamental human rights, right to vote, right to education, right to free speech) and responsibilities (pay taxes, obey laws, participate in civic life, protect the environment, respect others\' rights). Good citizenship promotes national development.', tags: ['citizenship', 'rights', 'responsibilities', 'civic', 'Ghana'] },
  { id: 'soc-003', subject: 'social-studies', topic: 'environment', text: 'Environmental problems in Ghana: deforestation, illegal mining (galamsey), water pollution, soil erosion, desertification in northern regions. Solutions: reforestation, regulation of mining, waste management, renewable energy adoption, environmental education. Climate change threatens agriculture and coastal areas.', tags: ['environment', 'Ghana', 'deforestation', 'galamsey', 'pollution', 'climate change'] },

  // ─── HISTORY ───────────────────────────────────────────────────────────────
  { id: 'hist-001', subject: 'history', topic: 'ghana-independence', text: 'Ghana gained independence on 6th March 1957, becoming the first sub-Saharan African country to gain independence. Dr. Kwame Nkrumah led the Convention People\'s Party (CPP). The declaration was made at Old Polo Grounds (now Independence Square) in Accra. "Ghana our beloved country is free forever!"', tags: ['independence', 'Ghana', 'Nkrumah', '1957', 'CPP', 'Africa'] },
  { id: 'hist-002', subject: 'history', topic: 'slave-trade', text: 'The Trans-Atlantic Slave Trade (15th-19th centuries) involved the forced transportation of millions of Africans to the Americas. Causes: European demand for labour, African political instability, economic incentives. Effects: depopulation of Africa, economic underdevelopment, formation of African diaspora, racial discrimination.', tags: ['slave trade', 'trans-atlantic', 'Africa', 'history', 'colonialism'] },
  { id: 'hist-003', subject: 'history', topic: 'colonial-period', text: 'The Gold Coast (modern Ghana) was colonized by Britain in stages: 1874 (Colony proclaimed), 1901 (Ashanti annexed), 1902 (Northern Territories added). Colonial rule introduced: Western education, Christianity, cash crops (cocoa), new administrative structures. Resistance: Yaa Asantewaa war 1900, UGCC formed 1947.', tags: ['colonialism', 'Gold Coast', 'Ghana', 'Britain', 'history', 'Ashanti'] },
];

/**
 * Get all knowledge entries for a given subject
 */
function getBySubject(subject) {
  return KNOWLEDGE_BASE.filter(e => e.subject === subject.toLowerCase());
}

/**
 * Get all entries as flat text documents for BM25 indexing
 */
function getAllDocuments() {
  return KNOWLEDGE_BASE.map(entry => ({
    id: entry.id,
    text: `${entry.topic} ${entry.text} ${entry.tags.join(' ')}`,
    meta: entry,
  }));
}

module.exports = { KNOWLEDGE_BASE, getBySubject, getAllDocuments };
